import type { Metadata } from "next";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import "./globals.css";
import { IBM_Plex_Sans } from "next/font/google";

const ibnPlex = IBM_Plex_Sans({
  subsets: ["latin"],
  variable: "--font-ibm-plex-sans",
});

export const metadata: Metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${ibnPlex.variable} antialiased`}>
          {/*<header>*/}
          {/*  <SignedOut>*/}
          {/*    <SignInButton />*/}
          {/*    <SignUpButton />*/}
          {/*  </SignedOut>*/}
          {/*  <SignedIn>*/}
          {/*    <UserButton />*/}
          {/*  </SignedIn>*/}
          {/*</header>*/}
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
